InstagramAPI - PostList permission 지정 (2017.03.16) Expected Result : Still Fail since commit : ca454ff8173a380329663f841a62042e339914b6
FAIL: test_post_create (post.tests.tests_apis.PostTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/hanabee2/projects/wps-4th/instagram_api/django_app/post/tests/tests_apis.py", line 47, in test_post_create
    self.assertEqual(response.status_code, status.HTTP_201_CREATED)
AssertionError: 403 != 201

Signed-off-by: hanabee337 <hanabee337@gmail.com>